### ISSUE TITLE
Can't import library: Unexpected token '('

### ISSUE THREAD

**Issue by Developer-Mike** [adrienjoly/npm-pdfreader#118] opened 2022-05-01 09:25 UTC
**Describe the bug**
Can't import library

**Screenshots, outputs or logs**
PATH\node_modules\pdf2json\pdfparser.js:50
        #onPDFJSParseDataReady(data) {
                              ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (PATH\node_modules\pdfreader\PdfReader.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

- OS: Windows

**Comment by adrienjoly** [comment] 2022-05-01 09:35
Can you share your source code, so we can investigate the issue, please?

**Comment by Developer-Mike** [comment] 2022-05-01 09:38
Nothing fancy ;D. Just:
const { PdfReader } = require("pdfreader");

And the sample also doesn't work.

**Comment by adrienjoly** [comment] 2022-05-01 09:50
I'm not able to reproduce your problem, at this time. 

What version of Node.js are you using? Can you share your `package.json` files so we can check for conflicts?

Also, can you checkout that other repo and try to run the example as explained there: https://github.com/adrienjoly/npm-pdfreader-example#how-to-install-and-run ?

**Comment by Developer-Mike** [comment] 2022-05-01 09:52
Node version: v12.16.3
Dependencies: "dependencies": {
    "express": "^4.18.1",
    "node-cron": "^3.0.0",
    "nodemon": "^2.0.16",
    "pdfreader": "^2.0.0"
  }

**Comment by adrienjoly** [comment] 2022-05-01 10:01
Ok!

As stated in the [release note of pdfreader 2.0](https://github.com/adrienjoly/npm-pdfreader/releases/tag/v2.0.0), Node.js 12 is not supported anymore.

Can you try upgrading to Node.js 14, and tell me if it works as expected?

**Comment by Developer-Mike** [comment] 2022-05-01 10:03
Thanks, I'll try it later

**Comment by adrienjoly** [comment] 2022-05-01 10:07
Ok. I'm closing this issue because Node's version mismatch is probably the reason why it does not work.

If you really need to use Node.js, feel free to use version 1 of pdfreader.

If you're still not able to make it work despite these solutions, feel free to re-open this issue.

**Closed by adrienjoly** 2022-05-01 10:07 UTC
