### ISSUE TITLE
loadMetaData error: TypeError: Cannot read property 'metadata' of null

### ISSUE THREAD

**Issue by mxs17** [adrienjoly/npm-pdfreader#93] opened 2021-10-24 11:16 UTC
Hello! 

I have been using `pdfreader` for some time, both locally on MacOS and in Docker, Node 15.14.0, and everything worked flawlessly. After updating project dependencies, I am getting the following output for any PDF files:
```
Warning: Setting up fake worker.
loadMetaData error: TypeError: Cannot read property 'metadata' of null
{
  parserError: "loadMetaData error: TypeError: Cannot read property 'metadata' of null"
}
```
I have created a clean project with the only dependency `"pdfreader": "^1.2.12"` and an example code from the documentation:
```javascript
const { PdfReader } = require("pdfreader");
const fs = require("fs");

fs.readFile("./sample.pdf", (err, pdfBuffer) => {
  new PdfReader().parseBuffer(pdfBuffer, function (err, item) {
    if (err) console.log(err);
    else if (!item) console.log("no item");
    else if (item.text) console.log(item.text);
  });
});
```
...and I am still getting the same message. I played with with versions of `pdfkit` and `pdf2json`, but did not solve the problem.

Update: this error appears on `1.2.12`. With `1.2.11`, it works properly.

**Comment by adrienjoly** [comment] 2021-11-11 10:01
What's up, mxs17? Any findings?

This problem may be indirectly caused by the fact that the version of `pdf2json` specified in our package.json was not necessarily respected when installing `pdfreader` as a dependency of your project, and `pdf2json` recently published a breaking change without respecting semantic versioning rules. See #95 for context.

=> Can you try upgrading `pdfreader` to today's version and tell us if that fixes your issue?

**Comment by mxs17** [comment] 2021-11-11 10:08
Hello! I created an [issue](https://github.com/modesty/pdf2json/issues/249) in `pdf2json` repo. It was confirmed that 1.2.5 -> 1.3.0 update introduced an error with metadata. Now I see the stable release is 1.2.5. I will check the current version of `pdfreader` in an hour.

**Comment by mxs17** [comment] 2021-11-11 10:16
I have upgraded my sample project to the current version of `pdfreader` `1.2.13`, and I can confirm the problem is solved. I see `pdf2json` `1.2.5` in `package-lock.json`. Thanks!

**Comment by adrienjoly** [comment] 2021-11-11 10:18
Awesome, thank you for the feedback!

I'm closing this issue. Feel free to re-open if the problem appears again.

Have a great day!

Adrien

**Closed by adrienjoly** 2021-11-11 10:18 UTC
