### ISSUE TITLE
No Response for the file of 150 MB which has 10000 pages. Can you please help me.

### ISSUE THREAD

**Issue by dlsagayaraj** [adrienjoly/npm-pdfreader#17] opened 2018-04-28 22:01 UTC
Hi, I am using the npm pdfreader. The code is not responding for a file of 150 MB which has 10000 pages. 

Below is my code. 

var pdfreader = require('pdfreader');

new pdfreader.PdfReader().parseFileItems('demo.pdf', function(err, item){
     console.log(item.text)
 });

Thank you for the help in advance.

**Comment by adrienjoly** [comment] 2018-04-29 17:07
Hi! Thanks for reporting this issue!

What do you mean by "not responding"? For how long have you waited?

As stated on [this issue from the pdf2json dependency](https://github.com/modesty/pdf2json/issues/70#issue-161739934), it may take 10 minutes for pdf2json to parse a 500-pages PDF file!

In response to that, here's a list of things you could try to do:
- the author of pdf2json recommends to split the file into smaller files (i.e. using another tool) before parsing it in your script (https://github.com/modesty/pdf2json/issues/70#issuecomment-230127197)
- another user suggested that performance problems could be caused by the structure of the PDF file rather than its size (https://github.com/modesty/pdf2json/issues/70#issuecomment-238869890), and proposed to help debugging on such issues
- you may try to fork pdf2json in order to change the way it parses pages, as proposed on https://github.com/modesty/pdf2json/issues/121
- you may otherwise want to use a command-line tool (e.g. [pdftojson](https://github.com/ldenoue/pdftojson)) to convert the PDF into JSON and then have your script run on the resulting JSON file

Hope this helps! Please let us know how it goes!

**Comment by adrienjoly** [comment] 2018-12-02 10:55
No reply since April => closing issue.

Feel free to re-open if needed.

**Closed by adrienjoly** 2018-12-02 10:55 UTC
Labels: help wanted, question
